# Generated by Django 3.1.7 on 2021-02-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_apis_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10, null=True)),
                ('api_method', models.CharField(max_length=10, null=True)),
                ('api_url', models.CharField(max_length=1000, null=True)),
                ('api_header', models.CharField(max_length=1000, null=True)),
                ('api_login', models.CharField(max_length=10, null=True)),
                ('api_host', models.CharField(max_length=100, null=True)),
                ('body_method', models.CharField(max_length=20, null=True)),
                ('api_body', models.CharField(max_length=1000, null=True)),
                ('sign', models.CharField(max_length=10, null=True)),
                ('file_key', models.CharField(max_length=50, null=True)),
                ('file_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='db_apis',
            name='body_method',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
