# Generated by Django 3.1.7 on 2021-02-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_api', '0002_auto_20210226_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
