# Generated by Django 3.1.7 on 2021-03-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_api', '0002_authuser_dbapis_dbapislog_dbcases_dbglobaldata_dbhomehref_dbhost_dblogin_dbproject_dbprojectheader_d'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'db_session',
                'managed': False,
            },
        ),
    ]
