# Generated by Django 3.1.7 on 2021-03-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_api', '0003_dbsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts_method', models.CharField(max_length=255, null=True)),
                ('ts_url', models.CharField(max_length=255, null=True)),
                ('ts_header', models.CharField(max_length=255, null=True)),
                ('ts_body_method', models.CharField(max_length=255, null=True)),
                ('ts_api_body', models.CharField(max_length=255, null=True)),
                ('ts_api_method', models.CharField(max_length=255, null=True)),
                ('is_delete', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'db_api',
                'managed': False,
            },
        ),
    ]
