# Generated by Django 3.1.7 on 2021-03-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_api', '0004_dbapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('failure_time', models.DateTimeField()),
                ('is_failure', models.IntegerField()),
            ],
            options={
                'db_table': 'user_token',
                'managed': False,
            },
        ),
    ]
