# Generated by Django 3.1.7 on 2021-03-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_api', '0010_db_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_step',
            name='api_login',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
