# Generated by Django 3.1.7 on 2021-03-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_api', '0011_db_step_api_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_global_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('user_id', models.CharField(max_length=10, null=True)),
                ('data', models.TextField(null=True)),
            ],
        ),
    ]
